# Generated by Django 4.2.7 on 2023-12-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_userprofile_age_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='chart_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
