# Generated by Django 4.2.7 on 2023-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_chart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chart_id',
            field=models.CharField(default='default_chart_id', max_length=100),
        ),
    ]
